[env:waveshare-169]
platform = espressif32
framework = arduino
board = waveshare_esp32s3_touch_lcd_169_v2
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

lib_deps =
    SPI
    bodmer/TFT_eSPI@^2.5.43
    bitbank2/JPEGDEC@^1.2.6

monitor_filters =
    esp32_exception_decoder

build_flags =
    -Ofast
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DWIFI_SSID=\"iptimesbj\"
    -DWIFI_PASSWORD=\"@sbj0116sbj\"
    -DSERVER_HOST=\"168.107.29.57\"
    -DSERVER_PORT=9000
    -DAPI_PORT=9001
    -DUSER_SETUP_LOADED=1
    -DST7789_2_DRIVER=1
    -DTFT_RGB_ORDER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=280
    -DTFT_MOSI=GPIO_NUM_7
    -DTFT_SCLK=GPIO_NUM_6
    -DTFT_CS=GPIO_NUM_5
    -DTFT_DC=GPIO_NUM_4
    -DTFT_RST=GPIO_NUM_8
    -DTFT_BL=GPIO_NUM_15
    -DTFT_MISO=GPIO_NUM_21
    -DSPI_FREQUENCY=80000000
    -DTFT_SPI_HOST=2
    -DTFT_Y_OFFSET=20
    -DUSE_HSPI_PORT
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
